export interface ICompanyDetails {
    acronym: string,
    bannerUrl: any,
    brief: string,
    createdBy: string,
    dateCreated: string,
    dateLastUpdated: string,
    description: string,
    email: string,
    id: string,
    industryId: string,
    isActive: boolean,
    lastUpdatedBy: string,
    logoUrl: any,
    rcNumber: string,
    shortName: string,
    timezoneId: any,
    tin: string,
    tinRegisteredName: string,
    type: number,
    website: string,
}